# Load plugins.
set -g @plugin 'tmux-plugins/tmux-sensible'      # Basic settings
set -g @plugin 'tmux-plugins/tmux-pain-control'    # Standard pane keybindings
set -g @plugin 'tmux-plugins/tmux-yank'        # Cross-platform support for clipboard.
set -g @plugin 'tmux-plugins/tmux-resurrect'   # Save/Restore sessions
set -g @plugin 'tmux-plugins/tmux-continuum'   # Auto Save/Restore

# Remap prefix to ctrl-a for screen consistency.
# set -g prefix C-a

# Restore using continuum.
set -g @continuum-restore 'on'
set -g @continuum-boot-options 'iterm'

# Shell management.

    # Set the default shell, and set the default command to use our shell (this
    # means we source things properly, show the correct PS1 etc).
    set -g default-shell ${SHELL} 
    set -g default-command ${SHELL}

# Mouse management.

    # Enable mouse mode (tmux 2.1 and above)
    set -g mouse on

# Colour management (yikes).

    # Use 256 colours.
    set-option -ga terminal-overrides ",xterm-256color:Tc"
    set-option -g default-terminal "screen-256color"

# Keyboard Management.

    # Don't wait for an escape sequence after hitting
    # Esc. fixes insert mode exit lag in vim.
    set -sg escape-time 0

# Clipboard / Copy / Paste
# Note: This is heavily OS dependent, which is why we have separate versions
# for OSX, Ubuntu etc. I'm trying out tmux-yank for this but it is still work in
# progress.

    # Use vim keybindings in copy mode
    setw -g mode-keys vi

    # Setup 'v' begin/end selection as in Vim.
    bind-key -T copy-mode-vi v send-keys -X begin-selection

# Pane and Window Management.

    # Open new panes and splits in the same working directory.
    bind c new-window -c "#{pane_current_path}"

## Status bar design
# set -g status-utf8 on
set -g status-justify left
set -g status-bg default
set -g status-interval 2

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'